In [43]:
import pandas as pd
import numpy as np

In [44]:
tbl = pd.read_html("https://zhenhub.com/blog/what-are-hs-hts-codes/")

In [45]:
tbl

[             0                                          1                   2
 0     SECTIONS                                   CATEGORY            CHAPTERS
 1    Section 1                   Animal & Animal Products         Chapter 1-5
 2    Section 2                         Vegetable Products       Chapters 6-14
 3    Section 3          Animal or Vegetable Fats and Oils          Chapter 15
 4    Section 4                        Prepared Foodstuffs       Chapter 16-24
 5    Section 5                           Mineral Products       Chapter 25-27
 6    Section 6              Chemicals & Allied Industries       Chapter 28-38
 7    Section 7                         Plastics / Rubbers  Chapters 39 and 40
 8    Section 8          Raw Hides, Skins, Leather, & Furs       Chapter 41-43
 9    Section 9                       Wood & Wood Products      Chapters 44-46
 10  Section 10  Pulp of Wood or of Other Fibrous Material      Chapters 47-49
 11  Section 11                                   Textiles      Chapters 50-63
 12  Section 12                        Footwear / Headgear      Chapters 64-67
 13  Section 13                              Stone / Glass      Chapters 68-70
 14  Section 14                 Natural or Cultured Pearls          Chapter 71
 15  Section 15                                Base Metals      Chapters 72-83
 16  Section 16                     Machinery / Electrical      Chapters 84-85
 17  Section 17                             Transportation      Chapters 86-89
 18  Section 18                      Precision Instruments      Chapters 90-92
 19  Section 19                        Arms and Ammunition         Chapters 93
 20  Section 20        Miscellaneous Manufactured Articles      Chapters 94-96
 21  Section 21                               Works of Art          Chapter 97]

In [46]:
tbl = tbl[0]

In [47]:
tbl.columns = tbl.iloc[0]

In [48]:
tbl = tbl.iloc[1:,:]

In [49]:
tbl

0     SECTIONS                                   CATEGORY            CHAPTERS
1    Section 1                   Animal & Animal Products         Chapter 1-5
2    Section 2                         Vegetable Products       Chapters 6-14
3    Section 3          Animal or Vegetable Fats and Oils          Chapter 15
4    Section 4                        Prepared Foodstuffs       Chapter 16-24
5    Section 5                           Mineral Products       Chapter 25-27
6    Section 6              Chemicals & Allied Industries       Chapter 28-38
7    Section 7                         Plastics / Rubbers  Chapters 39 and 40
8    Section 8          Raw Hides, Skins, Leather, & Furs       Chapter 41-43
9    Section 9                       Wood & Wood Products      Chapters 44-46
10  Section 10  Pulp of Wood or of Other Fibrous Material      Chapters 47-49
11  Section 11                                   Textiles      Chapters 50-63
12  Section 12                        Footwear / Headgear      Chapters 64-67
13  Section 13                              Stone / Glass      Chapters 68-70
14  Section 14                 Natural or Cultured Pearls          Chapter 71
15  Section 15                                Base Metals      Chapters 72-83
16  Section 16                     Machinery / Electrical      Chapters 84-85
17  Section 17                             Transportation      Chapters 86-89
18  Section 18                      Precision Instruments      Chapters 90-92
19  Section 19                        Arms and Ammunition         Chapters 93
20  Section 20        Miscellaneous Manufactured Articles      Chapters 94-96
21  Section 21                               Works of Art          Chapter 97

In [50]:
tbl['HS HEAD CODE'] = ["0101-0599","0601-1499","1501-1599","1600-2400","2500-2700","2800-3800","3900-4000","4100-4300","4400-4600","4700-4900","5000-6300","6400-6700","6800-7000","7100-7199","7200-8300","8400-8500","8600-8900","9000-9200","9300-9399","9400-9600","9700-9799"]

C:\Users\Mence\AppData\Local\Temp\ipykernel_17628\4148057122.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tbl['HS HEAD CODE'] = ["0101-0599","0601-1499","1501-1599","1600-2400","2500-2700","2800-3800","3900-4000","4100-4300","4400-4600","4700-4900","5000-6300","6400-6700","6800-7000","7100-7199","7200-8300","8400-8500","8600-8900","9000-9200","9300-9399","9400-9600","9700-9799"]

In [51]:
tbl

,SECTIONS,CATEGORY,CHAPTERS,HS HEAD CODE
1,Section 1,Animal & Animal Products,Chapter 1-5,0101-0599
2,Section 2,Vegetable Products,Chapters 6-14,0601-1499
3,Section 3,Animal or Vegetable Fats and Oils,Chapter 15,1501-1599
4,Section 4,Prepared Foodstuffs,Chapter 16-24,1600-2400
5,Section 5,Mineral Products,Chapter 25-27,2500-2700
6,Section 6,Chemicals & Allied Industries,Chapter 28-38,2800-3800
7,Section 7,Plastics / Rubbers,Chapters 39 and 40,3900-4000
8,Section 8,"Raw Hides, Skins, Leather, & Furs",Chapter 41-43,4100-4300
9,Section 9,Wood & Wood Products,Chapters 44-46,4400-4600
10,Section 10,Pulp of Wood or of Other Fibrous Material,Chapters 47-49,4700-4900
11,Section 11,Textiles,Chapters 50-63,5000-6300
12,Section 12,Footwear / Headgear,Chapters 64-67,6400-6700
13,Section 13,Stone / Glass,Chapters 68-70,6800-7000
14,Section 14,Natural or Cultured Pearls,Chapter 71,7100-7199
15,Section 15,Base Metals,Chapters 72-83,7200-8300
16,Section 16,Machinery / Electrical,Chapters 84-85,8400-8500
17,Section 17,Transportation,Chapters 86-89,8600-8900
18,Section 18,Precision Instruments,Chapters 90-92,9000-9200
19,Section 19,Arms and Ammunition,Chapters 93,9300-9399
20,Section 20,Miscellaneous Manufactured Articles,Chapters 94-96,9400-9600
21,Section 21,Works of Art,Chapter 97,9700-9799

In [53]:
tbl.to_csv('HSCODE HEADERS.csv')

In [54]:
tbl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 1 to 21
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SECTIONS      21 non-null     object
 1   CATEGORY      21 non-null     object
 2   CHAPTERS      21 non-null     object
 3   HS HEAD CODE  21 non-null     object
dtypes: object(4)
memory usage: 804.0+ bytes

In [55]:
tbl.astype({'HS HEAD CODE':'int'})

ValueError: invalid literal for int() with base 10: '0101-0599'